# Data Gathering

In [79]:
import pandas as pd

In [80]:
df_train=pd.read_csv("twitter_training.csv")

In [81]:
df_train

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [82]:
df_train=df_train.sample(15000)

In [83]:
df_train.shape

(15000, 4)

In [84]:
df_train['Positive'].value_counts()

Positive
Negative      4528
Positive      4193
Neutral       3667
Irrelevant    2612
Name: count, dtype: int64

In [85]:
df_train.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    133
dtype: int64

In [86]:
df_train.duplicated().sum()

119

# Data cleaning

In [87]:
df_train=df_train.dropna()

In [88]:
df_train.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [89]:
df_train.shape

(14867, 4)

In [90]:
df_train.drop_duplicates(inplace=True)

In [91]:
df_train.duplicated().sum()

0

In [92]:
df_train

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
59021,3318,Facebook,Negative,Mark Zuckerberg has been part of the problem f...
28126,441,ApexLegends,Irrelevant,Fucking need this man IMMEDIATELY to K
36462,8257,Microsoft,Positive,So Microsoft designed its new colorful Windows...
60204,3517,Facebook,Neutral,@ BJP4Bengal's Rimjhim Mitra makes misleading ...
34015,6642,Fortnite,Negative,i.tt / 2HYjBNt i.tt / 3a3cM9k What did they do...
...,...,...,...,...
13236,8673,NBA2K,Positive,"It looks really good, except for 2 little thin..."
65731,6858,johnson&johnson,Neutral,"Johnson & Johnson (JNJ) Stock Down 2% Today, C..."
59465,3394,Facebook,Neutral,The way I want to close down my Facebook but I...
6377,297,Amazon,Neutral,The Best Amazon Review For . . protect your d...
72506,8821,Nvidia,Neutral,Amazing deal for you!.. Lenovo Legion 8<unk> G...

In [93]:
df_train=df_train.drop(columns=['2401','Borderlands'])

In [94]:
df_train

         Positive im getting on borderlands and i will murder you all ,
59021    Negative  Mark Zuckerberg has been part of the problem f...
28126  Irrelevant             Fucking need this man IMMEDIATELY to K
36462    Positive  So Microsoft designed its new colorful Windows...
60204     Neutral  @ BJP4Bengal's Rimjhim Mitra makes misleading ...
34015    Negative  i.tt / 2HYjBNt i.tt / 3a3cM9k What did they do...
...           ...                                                ...
13236    Positive  It looks really good, except for 2 little thin...
65731     Neutral  Johnson & Johnson (JNJ) Stock Down 2% Today, C...
59465     Neutral  The way I want to close down my Facebook but I...
6377      Neutral  The Best Amazon Review For  . . protect your d...
72506     Neutral  Amazing deal for you!.. Lenovo Legion 8<unk> G...

[14765 rows x 2 columns]

In [95]:
df_train.rename(columns={'Positive':'Sentiment', 'im getting on borderlands and i will murder you all ,':'Tweets'}, inplace=True)

In [96]:
df_train

        Sentiment                                             Tweets
59021    Negative  Mark Zuckerberg has been part of the problem f...
28126  Irrelevant             Fucking need this man IMMEDIATELY to K
36462    Positive  So Microsoft designed its new colorful Windows...
60204     Neutral  @ BJP4Bengal's Rimjhim Mitra makes misleading ...
34015    Negative  i.tt / 2HYjBNt i.tt / 3a3cM9k What did they do...
...           ...                                                ...
13236    Positive  It looks really good, except for 2 little thin...
65731     Neutral  Johnson & Johnson (JNJ) Stock Down 2% Today, C...
59465     Neutral  The way I want to close down my Facebook but I...
6377      Neutral  The Best Amazon Review For  . . protect your d...
72506     Neutral  Amazing deal for you!.. Lenovo Legion 8<unk> G...

[14765 rows x 2 columns]

In [97]:
df_train=df_train[(df_train['Sentiment']=='Positive') | (df_train['Sentiment']=='Negative') | (df_train['Sentiment']=='Neutral')]

In [98]:
df_train

      Sentiment                                             Tweets
59021  Negative  Mark Zuckerberg has been part of the problem f...
36462  Positive  So Microsoft designed its new colorful Windows...
60204   Neutral  @ BJP4Bengal's Rimjhim Mitra makes misleading ...
34015  Negative  i.tt / 2HYjBNt i.tt / 3a3cM9k What did they do...
66981  Positive  Jim Cramer : Johnson & Johnson vaccine a candi...
...         ...                                                ...
13236  Positive  It looks really good, except for 2 little thin...
65731   Neutral  Johnson & Johnson (JNJ) Stock Down 2% Today, C...
59465   Neutral  The way I want to close down my Facebook but I...
6377    Neutral  The Best Amazon Review For  . . protect your d...
72506   Neutral  Amazing deal for you!.. Lenovo Legion 8<unk> G...

[12188 rows x 2 columns]

In [99]:
df_train['Sentiment'].value_counts()

Sentiment
Negative    4472
Positive    4116
Neutral     3600
Name: count, dtype: int64

# Feature encoding

In [100]:
from sklearn.preprocessing import LabelEncoder

In [101]:
le=LabelEncoder()

In [102]:
df_train['Sentiment']=le.fit_transform(df_train['Sentiment'])

C:\Users\Ankit\AppData\Local\Temp\ipykernel_10620\2661879071.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['Sentiment']=le.fit_transform(df_train['Sentiment'])

In [103]:
df_train

       Sentiment                                             Tweets
59021          0  Mark Zuckerberg has been part of the problem f...
36462          2  So Microsoft designed its new colorful Windows...
60204          1  @ BJP4Bengal's Rimjhim Mitra makes misleading ...
34015          0  i.tt / 2HYjBNt i.tt / 3a3cM9k What did they do...
66981          2  Jim Cramer : Johnson & Johnson vaccine a candi...
...          ...                                                ...
13236          2  It looks really good, except for 2 little thin...
65731          1  Johnson & Johnson (JNJ) Stock Down 2% Today, C...
59465          1  The way I want to close down my Facebook but I...
6377           1  The Best Amazon Review For  . . protect your d...
72506          1  Amazing deal for you!.. Lenovo Legion 8<unk> G...

[12188 rows x 2 columns]

In [104]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [105]:
tokenizer=Tokenizer(oov_token='Nothing')   # any token outside the vocab in the training will be considered as 'Nothing'

In [106]:
tokenizer.fit_on_texts(df_train['Tweets'])

In [107]:
df_train

       Sentiment                                             Tweets
59021          0  Mark Zuckerberg has been part of the problem f...
36462          2  So Microsoft designed its new colorful Windows...
60204          1  @ BJP4Bengal's Rimjhim Mitra makes misleading ...
34015          0  i.tt / 2HYjBNt i.tt / 3a3cM9k What did they do...
66981          2  Jim Cramer : Johnson & Johnson vaccine a candi...
...          ...                                                ...
13236          2  It looks really good, except for 2 little thin...
65731          1  Johnson & Johnson (JNJ) Stock Down 2% Today, C...
59465          1  The way I want to close down my Facebook but I...
6377           1  The Best Amazon Review For  . . protect your d...
72506          1  Amazing deal for you!.. Lenovo Legion 8<unk> G...

[12188 rows x 2 columns]

In [108]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'to': 3,
 'i': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'it': 11,
 'this': 12,
 'my': 13,
 'you': 14,
 'on': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'just': 21,
 'me': 22,
 'be': 23,
 'have': 24,
 'but': 25,
 'not': 26,
 'are': 27,
 'all': 28,
 'was': 29,
 'at': 30,
 'like': 31,
 '2': 32,
 'pic': 33,
 'from': 34,
 'get': 35,
 'twitter': 36,
 'your': 37,
 'now': 38,
 'out': 39,
 'we': 40,
 'play': 41,
 'johnson': 42,
 't': 43,
 'good': 44,
 'if': 45,
 'can': 46,
 'they': 47,
 'one': 48,
 'as': 49,
 'no': 50,
 'about': 51,
 'really': 52,
 'do': 53,
 'new': 54,
 'has': 55,
 'an': 56,
 'love': 57,
 'when': 58,
 "i'm": 59,
 'will': 60,
 '3': 61,
 'some': 62,
 'or': 63,
 'time': 64,
 'more': 65,
 'unk': 66,
 'what': 67,
 'up': 68,
 'why': 69,
 'by': 70,
 'amazon': 71,
 'shit': 72,
 'co': 73,
 'how': 74,
 "it's": 75,
 'still': 76,
 'people': 77,
 'https': 78,
 'best': 79,
 'games': 80,
 'been': 81,
 'facebook': 82,
 'verizon': 83,
 'see': 84,
 'playing': 85,
 '1': 86,
 '’': 87,
 'got': 88,
 'fuck': 89,
 'xbox': 90,
 'dead': 91,
 'please': 92,
 'fucking': 93,
 'microsoft': 94,
 'rhandlerr': 95,
 'because': 96,
 'red': 97,
 'great': 98,
 'even': 99,
 'them': 100,
 'us': 101,
 'go': 102,
 'much': 103,
 'going': 104,
 'there': 105,
 'google': 106,
 'am': 107,
 'had': 108,
 'only': 109,
 'who': 110,
 '5': 111,
 'after': 112,
 's': 113,
 'home': 114,
 'back': 115,
 'nvidia': 116,
 'make': 117,
 'fix': 118,
 "can't": 119,
 'their': 120,
 'its': 121,
 'over': 122,
 'borderlands': 123,
 'eamaddennfl': 124,
 'very': 125,
 'tv': 126,
 'day': 127,
 "don't": 128,
 'know': 129,
 'fun': 130,
 '2020': 131,
 'would': 132,
 '4': 133,
 'want': 134,
 'first': 135,
 'today': 136,
 'these': 137,
 'redemption': 138,
 'our': 139,
 'than': 140,
 'here': 141,
 'fifa': 142,
 'wait': 143,
 '…': 144,
 'again': 145,
 'also': 146,
 'most': 147,
 'league': 148,
 'thank': 149,
 'rainbow6game': 150,
 'x': 151,
 'nba2k': 152,
 'legends': 153,
 'pubg': 154,
 'too': 155,
 'ever': 156,
 'thanks': 157,
 'world': 158,
 'twitch': 159,
 'ps5': 160,
 'guys': 161,
 'getting': 162,
 'depot': 163,
 'u': 164,
 'off': 165,
 'never': 166,
 'bad': 167,
 'news': 168,
 'work': 169,
 'he': 170,
 'video': 171,
 'right': 172,
 'call': 173,
 'series': 174,
 'gta': 175,
 'help': 176,
 'then': 177,
 'year': 178,
 "i've": 179,
 'think': 180,
 'looks': 181,
 'damn': 182,
 'watch': 183,
 'last': 184,
 'every': 185,
 'down': 186,
 'v': 187,
 'well': 188,
 '10': 189,
 'being': 190,
 'any': 191,
 'into': 192,
 'creed': 193,
 'amazing': 194,
 'buy': 195,
 'ghostrecon': 196,
 'warcraft': 197,
 'man': 198,
 'happy': 199,
 'actually': 200,
 'e': 201,
 'overwatch': 202,
 'another': 203,
 'did': 204,
 'played': 205,
 'i’m': 206,
 'next': 207,
 'black': 208,
 'need': 209,
 'youtu': 210,
 'could': 211,
 'hearthstone': 212,
 'stop': 213,
 'say': 214,
 'live': 215,
 'wtf': 216,
 'always': 217,
 'everyone': 218,
 'take': 219,
 'years': 220,
 'players': 221,
 'other': 222,
 'update': 223,
 'youtube': 224,
 'made': 225,
 'while': 226,
 'free': 227,
 'were': 228,
 'excited': 229,
 'big': 230,
 'it’s': 231,
 'fortnite': 232,
 'support': 233,
 'money': 234,
 'should': 235,
 'duty': 236,
 'nice': 237,
 'which': 238,
 'give': 239,
 'look': 240,
 'way': 241,
 'online': 242,
 'via': 243,
 '6': 244,
 'many': 245,
 'battlefield': 246,
 '20': 247,
 'team': 248,
 'better': 249,
 'since': 250,
 'csgo': 251,
 'wow': 252,
 'store': 253,
 'win': 254,
 'come': 255,
 'finally': 256,
 'keep': 257,
 'his': 258,
 'gonna': 259,
 'ubisoft': 260,
 'having': 261,
 'something': 262,
 'playapex': 263,
 'stream': 264,
 'thing': 265,
 'where': 266,
 'things': 267,
 'trying': 268,
 'such': 269,
 'pc': 270,
 'bit': 271,
 'already': 272,
 'done': 273,
 'looking': 274,
 'same': 275,
 'someone': 276,
 '100': 277,
 'ass': 278,
 'company': 279,
 'hate': 280,
 'before': 281,
 'health': 282,
 'through': 283,
 'baby': 284,
 'oh': 285,
 'him': 286,
 'everything': 287,
 'two': 288,
 'access': 289,
 'days': 290,
 'awesome': 291,
 'care': 292,
 'lol': 293,
 'problem': 294,
 'm': 295,
 'playstation': 296,
 'account': 297,
 'doing': 298,
 'war': 299,
 'check': 300,
 'servers': 301,
 'her': 302,
 'hey': 303,
 'both': 304,
 'long': 305,
 'real': 306,
 'old': 307,
 'nothing': 308,
 'mobile': 309,
 'dota': 310,
 'ly': 311,
 'until': 312,
 'powder': 313,
 'lot': 314,
 'cool': 315,
 'ea': 316,
 'super': 317,
 'hell': 318,
 'uk': 319,
 'pretty': 320,
 'use': 321,
 'making': 322,
 'life': 323,
 'cyberpunk': 324,
 'feel': 325,
 'does': 326,
 'god': 327,
 'im': 328,
 '2077': 329,
 '7': 330,
 'night': 331,
 'try': 332,
 'let': 333,
 'probably': 334,
 '•': 335,
 'card': 336,
 'story': 337,
 'top': 338,
 'mode': 339,
 'service': 340,
 'little': 341,
 "that's": 342,
 'start': 343,
 'favorite': 344,
 'interesting': 345,
 'worst': 346,
 "doesn't": 347,
 '19': 348,
 'whole': 349,
 'literally': 350,
 'almost': 351,
 'week': 352,
 'ps4': 353,
 'hours': 354,
 'few': 355,
 'won': 356,
 'player': 357,
 'tonight': 358,
 'far': 359,
 'phone': 360,
 'ranked': 361,
 'assassins': 362,
 'cold': 363,
 'internet': 364,
 'can’t': 365,
 'those': 366,
 'working': 367,
 'miss': 368,
 'chance': 369,
 'around': 370,
 'sure': 371,
 'anyone': 372,
 'lost': 373,
 'ops': 374,
 'yet': 375,
 'pay': 376,
 'against': 377,
 'without': 378,
 'hope': 379,
 'hard': 380,
 'season': 381,
 'run': 382,
 'apex': 383,
 'show': 384,
 'makes': 385,
 'maybe': 386,
 'app': 387,
 '21': 388,
 'release': 389,
 'y’all': 390,
 '30': 391,
 'epic': 392,
 "y'all": 393,
 'italy': 394,
 'end': 395,
 'said': 396,
 'gaming': 397,
 'd': 398,
 'order': 399,
 'enjoy': 400,
 'vaccine': 401,
 'callofduty': 402,
 'gets': 403,
 'console': 404,
 'find': 405,
 'part': 406,
 'month': 407,
 'stuff': 408,
 'madden': 409,
 'cant': 410,
 'crazy': 411,
 '15': 412,
 'skin': 413,
 'ban': 414,
 'beautiful': 415,
 'stupid': 416,
 '2k': 417,
 'open': 418,
 'friends': 419,
 'w': 420,
 'point': 421,
 'bought': 422,
 'anything': 423,
 'kill': 424,
 'guy': 425,
 'times': 426,
 'thought': 427,
 'don’t': 428,
 'minutes': 429,
 'post': 430,
 'may': 431,
 'selling': 432,
 'broken': 433,
 'full': 434,
 'tried': 435,
 'trash': 436,
 'wrong': 437,
 'forward': 438,
 'org': 439,
 'went': 440,
 'absolutely': 441,
 'sad': 442,
 'tell': 443,
 "i'll": 444,
 'watching': 445,
 'hit': 446,
 '0': 447,
 'homedepot': 448,
 'found': 449,
 'share': 450,
 'buying': 451,
 "didn't": 452,
 'own': 453,
 'used': 454,
 '9': 455,
 'perfect': 456,
 'exciting': 457,
 'gameplay': 458,
 'terrible': 459,
 'reason': 460,
 'business': 461,
 '12': 462,
 'though': 463,
 'banned': 464,
 "you're": 465,
 "assassin's": 466,
 'says': 467,
 'change': 468,
 'fact': 469,
 'line': 470,
 'services': 471,
 'covid': 472,
 'using': 473,
 'yall': 474,
 'launch': 475,
 'dont': 476,
 'based': 477,
 'sorry': 478,
 'grand': 479,
 'half': 480,
 'myself': 481,
 'huge': 482,
 'p': 483,
 'soon': 484,
 'tomorrow': 485,
 'data': 486,
 'taken': 487,
 'due': 488,
 'saying': 489,
 'tt': 490,
 "won't": 491,
 'running': 492,
 'enough': 493,
 'coming': 494,
 'talc': 495,
 'playhearthstone': 496,
 'place': 497,
 'myteam': 498,
 'cs': 499,
 'power': 500,
 'system': 501,
 'might': 502,
 'put': 503,
 'worth': 504,
 'million': 505,
 'definitely': 506,
 'yes': 507,
 'pro': 508,
 'idea': 509,
 'link': 510,
 'months': 511,
 'price': 512,
 'high': 513,
 'job': 514,
 'odyssey': 515,
 'seems': 516,
 'latest': 517,
 'cause': 518,
 'net': 519,
 'read': 520,
 'hi': 521,
 'trailer': 522,
 'face': 523,
 'cod': 524,
 'points': 525,
 'took': 526,
 'currently': 527,
 'instead': 528,
 'dlvr': 529,
 'anymore': 530,
 'server': 531,
 'least': 532,
 'patch': 533,
 'mean': 534,
 'entire': 535,
 'finished': 536,
 'sucks': 537,
 'eu': 538,
 'seen': 539,
 'n2k': 540,
 'match': 541,
 'issues': 542,
 'three': 543,
 'streaming': 544,
 'screen': 545,
 'gold': 546,
 'she': 547,
 'community': 548,
 'problems': 549,
 'seriously': 550,
 'luck': 551,
 'yo': 552,
 'i’ve': 553,
 'ago': 554,
 'c': 555,
 'morning': 556,
 'once': 557,
 'achievement': 558,
 'else': 559,
 'character': 560,
 "there's": 561,
 'feels': 562,
 'comes': 563,
 '8': 564,
 'event': 565,
 'content': 566,
 'dota2': 567,
 'experience': 568,
 'called': 569,
 'graphics': 570,
 'during': 571,
 'rtx': 572,
 'ok': 573,
 'must': 574,
 'cards': 575,
 'name': 576,
 'wanted': 577,
 'bro': 578,
 '”': 579,
 'friend': 580,
 'true': 581,
 'page': 582,
 'error': 583,
 'easports': 584,
 'y': 585,
 'rewards': 586,
 'person': 587,
 'able': 588,
 'seeing': 589,
 'blizzard': 590,
 'videos': 591,
 'edition': 592,
 'fans': 593,
 'version': 594,
 'remember': 595,
 'switch': 596,
 'worse': 597,
 'completely': 598,
 'ready': 599,
 'pre': 600,
 'step': 601,
 'away': 602,
 'tired': 603,
 'omg': 604,
 'earned': 605,
 'ghost': 606,
 'action': 607,
 'leagueoflegends': 608,
 'needs': 609,
 'ift': 610,
 'either': 611,
 'o': 612,
 'ronnie2k': 613,
 'giving': 614,
 'honestly': 615,
 'hot': 616,
 'cannot': 617,
 'tech': 618,
 'leave': 619,
 'windows': 620,
 'sony': 621,
 'easy': 622,
 'early': 623,
 'social': 624,
 'market': 625,
 'killed': 626,
 'apple': 627,
 'issue': 628,
 'die': 629,
 'commission': 630,
 'small': 631,
 'deal': 632,
 'spend': 633,
 'came': 634,
 'ubisoftsupport': 635,
 'review': 636,
 'fps': 637,
 'beluba': 638,
 'moment': 639,
 'suck': 640,
 'customer': 641,
 'different': 642,
 'loved': 643,
 'second': 644,
 'annoying': 645,
 'state': 646,
 'pass': 647,
 'glad': 648,
 'below': 649,
 'despite': 650,
 'past': 651,
 'lmao': 652,
 'yesterday': 653,
 'proud': 654,
 'final': 655,
 'happened': 656,
 'city': 657,
 'understand': 658,
 'report': 659,
 'family': 660,
 'current': 661,
 'companies': 662,
 'mind': 663,
 'less': 664,
 'bc': 665,
 'break': 666,
 'history': 667,
 'smh': 668,
 'move': 669,
 'holy': 670,
 '11': 671,
 'fortnitegame': 672,
 'class': 673,
 'speed': 674,
 'gift': 675,
 'goes': 676,
 'apps': 677,
 'absolute': 678,
 'wikipedia': 679,
 'connection': 680,
 'kind': 681,
 'franchise': 682,
 'wanna': 683,
 'stay': 684,
 'f': 685,
 'weekend': 686,
 'dlc': 687,
 'heart': 688,
 'fan': 689,
 'told': 690,
 'hour': 691,
 'global': 692,
 'cancer': 693,
 '99': 694,
 'delayed': 695,
 'sick': 696,
 'modern': 697,
 'music': 698,
 'sold': 699,
 'b': 700,
 'hello': 701,
 'major': 702,
 "haven't": 703,
 'breakpoint': 704,
 'r': 705,
 'hear': 706,
 'main': 707,
 'started': 708,
 'death': 709,
 'toxic': 710,
 'shot': 711,
 'okay': 712,
 'products': 713,
 'each': 714,
 'retweet': 715,
 'canada': 716,
 'complete': 717,
 'house': 718,
 'join': 719,
 'birthday': 720,
 'plays': 721,
 're': 722,
 'guess': 723,
 'list': 724,
 'waiting': 725,
 'starting': 726,
 'talk': 727,
 'bitch': 728,
 'especially': 729,
 'trial': 730,
 'lose': 731,
 'warzone': 732,
 'feeling': 733,
 'living': 734,
 'wants': 735,
 'sounds': 736,
 "we're": 737,
 'india': 738,
 'tweet': 739,
 'wish': 740,
 'email': 741,
 'shut': 742,
 "let's": 743,
 'head': 744,
 'later': 745,
 'bring': 746,
 'daily': 747,
 'article': 748,
 'kinda': 749,
 'mad': 750,
 'stuck': 751,
 'sound': 752,
 'mut': 753,
 'left': 754,
 "what's": 755,
 'plus': 756,
 'set': 757,
 'unit': 758,
 'moments': 759,
 'totally': 760,
 'bullshit': 761,
 'massive': 762,
 'yeah': 763,
 'original': 764,
 'follow': 765,
 'fantastic': 766,
 'gotta': 767,
 'funny': 768,
 'valhalla': 769,
 'rockstargames': 770,
 'number': 771,
 'gen': 772,
 'side': 773,
 'sell': 774,
 'cyberpunkgame': 775,
 'incredible': 776,
 'level': 777,
 'battle': 778,
 'warfare': 779,
 'weeks': 780,
 'decided': 781,
 'believe': 782,
 'saw': 783,
 'talking': 784,
 'works': 785,
 'heard': 786,
 'ai': 787,
 'men': 788,
 'between': 789,
 'together': 790,
 'wins': 791,
 'including': 792,
 'date': 793,
 'truly': 794,
 'keeps': 795,
 'playoverwatch': 796,
 'instagram': 797,
 'code': 798,
 'characters': 799,
 'continue': 800,
 'eahelp': 801,
 'search': 802,
 '–': 803,
 'stock': 804,
 'taking': 805,
 'stores': 806,
 'j': 807,
 'insane': 808,
 'en': 809,
 'classic': 810,
 'movie': 811,
 'tho': 812,
 'felt': 813,
 'pls': 814,
 'enjoyed': 815,
 'congratulations': 816,
 'book': 817,
 'ordered': 818,
 'single': 819,
 'edge': 820,
 'updates': 821,
 'clips': 822,
 'quiz': 823,
 'released': 824,
 'forever': 825,
 'performance': 826,
 'actual': 827,
 '“': 828,
 'test': 829,
 'random': 830,
 'nfl': 831,
 'media': 832,
 'boy': 833,
 'sea': 834,
 'rest': 835,
 'low': 836,
 'longer': 837,
 'iphone': 838,
 'official': 839,
 'teams': 840,
 'garbage': 841,
 'bugs': 842,
 'add': 843,
 'fast': 844,
 'special': 845,
 'ur': 846,
 'quality': 847,
 'twice': 848,
 "i'd": 849,
 'click': 850,
 'digital': 851,
 'seem': 852,
 'cuz': 853,
 'pick': 854,
 'brand': 855,
 'mask': 856,
 'ridiculous': 857,
 'chat': 858,
 'sense': 859,
 'broke': 860,
 'golden': 861,
 'trump': 862,
 'received': 863,
 'dear': 864,
 'plan': 865,
 'network': 866,
 'siege': 867,
 'customers': 868,
 'row': 869,
 'safe': 870,
 'map': 871,
 'fine': 872,
 'item': 873,
 "they're": 874,
 'plz': 875,
 'controller': 876,
 'biggest': 877,
 '3080': 878,
 'design': 879,
 'dying': 880,
 'drop': 881,
 'website': 882,
 'boycott': 883,
 'poverty': 884,
 'beta': 885,
 'changes': 886,
 'imagine': 887,
 'gg': 888,
 'matter': 889,
 'greatest': 890,
 'calls': 891,
 'info': 892,
 'auto': 893,
 'turn': 894,
 'reading': 895,
 'af': 896,
 've': 897,
 'gone': 898,
 'ultimate': 899,
 'party': 900,
 'sometimes': 901,
 '09': 902,
 'dope': 903,
 'possible': 904,
 'thinking': 905,
 'platform': 906,
 'computer': 907,
 'n': 908,
 'gpu': 909,
 'spent': 910,
 'site': 911,
 'download': 912,
 'hand': 913,
 'losing': 914,
 'killing': 915,
 'accounts': 916,
 'shows': 917,
 'become': 918,
 'that’s': 919,
 'welcome': 920,
 'quick': 921,
 'total': 922,
 'dumb': 923,
 "isn't": 924,
 'steam': 925,
 'rt': 926,
 '00': 927,
 'happens': 928,
 'white': 929,
 'slow': 930,
 'quit': 931,
 'art': 932,
 'decision': 933,
 '2019': 934,
 'shitty': 935,
 'android': 936,
 'except': 937,
 'available': 938,
 'lie': 939,
 'technology': 940,
 'cute': 941,
 'nba': 942,
 'kills': 943,
 'drive': 944,
 'means': 945,
 'outside': 946,
 'sort': 947,
 'articles': 948,
 'quite': 949,
 'stopped': 950,
 'employees': 951,
 'simply': 952,
 'prime': 953,
 'listen': 954,
 'forgot': 955,
 '01': 956,
 'sent': 957,
 'wonder': 958,
 'folks': 959,
 'lets': 960,
 'blue': 961,
 'crashes': 962,
 'crashing': 963,
 'source': 964,
 'career': 965,
 'gamer': 966,
 'wear': 967,
 'blog': 968,
 'information': 969,
 'alone': 970,
 'short': 971,
 'couple': 972,
 'save': 973,
 'cut': 974,
 'ps': 975,
 'cry': 976,
 'joke': 977,
 'important': 978,
 'dude': 979,
 'died': 980,
 'geforce': 981,
 'needed': 982,
 'box': 983,
 'finish': 984,
 'fire': 985,
 'entering': 986,
 'summoners': 987,
 'late': 988,
 'activision': 989,
 'sales': 990,
 'crap': 991,
 'mine': 992,
 'takes': 993,
 'shooting': 994,
 'gearboxofficial': 995,
 'fixed': 996,
 '13': 997,
 'close': 998,
 'masks': 999,
 'everyday': 1000,
 ...}

In [109]:
tokenizer.word_counts

OrderedDict([('mark', 18),
             ('zuckerberg', 10),
             ('has', 553),
             ('been', 399),
             ('part', 79),
             ('of', 3254),
             ('the', 7258),
             ('problem', 122),
             ('for', 2510),
             ('a', 3806),
             ('long', 114),
             ('time', 499),
             ('along', 26),
             ('with', 1457),
             ('sheryl', 2),
             ('sandberg', 2),
             ('who', 313),
             ('encouraged', 2),
             ('conspiracy', 7),
             ('theories', 3),
             ('about', 578),
             ('george', 8),
             ('soros', 3),
             ('on', 1980),
             ('facebook', 390),
             ('fb', 21),
             ('never', 221),
             ('neutral', 3),
             ('platform', 30),
             ('consider', 7),
             ('stole', 14),
             ('idea', 60),
             ('and', 4348),
             ('initially', 7),
             ('used', 70),
             ('it', 2406),
             ('to', 4887),
             ('ridicule', 1),
             ('women', 26),
             ('so', 1325),
             ('microsoft', 356),
             ('designed', 5),
             ('its', 288),
             ('new', 562),
             ('colorful', 3),
             ('windows', 47),
             ('10', 199),
             ('icons', 1),
             ('rouut', 3),
             ('com', 1614),
             ('02', 15),
             ('20', 149),
             ('2020', 265),
             ('thi', 2),
             ('https', 404),
             ('t', 598),
             ('co', 455),
             ('lzy5ssrur0', 2),
             ("bjp4bengal's", 1),
             ('rimjhim', 2),
             ('mitra', 2),
             ('makes', 86),
             ('misleading', 7),
             ('posts', 17),
             ('wbpolice', 2),
             ('kolkatapolice', 2),
             ('please', 358),
             ('look', 153),
             ('at', 894),
             ('this', 2342),
             ('take', 165),
             ('appropriate', 5),
             ('action', 48),
             ('link', 60),
             ('1059690706', 2),
             ('pos', 2),
             ('blizxnyoif', 2),
             ('i', 4789),
             ('tt', 64),
             ('2hyjbnt', 1),
             ('3a3cm9k', 2),
             ('what', 496),
             ('did', 176),
             ('they', 589),
             ('do', 573),
             ('purple', 11),
             ('glow', 1),
             ("paratrooper's", 1),
             ('skull', 3),
             ("that's", 97),
             ('why', 485),
             ("don't", 270),
             ('like', 813),
             ('fortnite', 157),
             ('deal', 46),
             ('things', 134),
             ('that', 1621),
             ("aren't", 18),
             ('broken', 74),
             ('jim', 6),
             ('cramer', 3),
             ('johnson', 613),
             ('vaccine', 80),
             ('candidate', 5),
             ('in', 2569),
             ('these', 260),
             ('stocks', 8),
             ('compelling', 2),
             ('okay', 41),
             ('year', 205),
             ('resolutions', 2),
             ('play', 616),
             ('more', 499),
             ('games', 402),
             ('beat', 20),
             ('game', 1459),
             ('every', 201),
             ('month', 79),
             ('buy', 189),
             ('xbox', 364),
             ('series', 210),
             ('x', 234),
             ('day', 272),
             ('1', 382),
             ('nvidia', 302),
             ('ti', 7),
             ('card', 100),
             ('spend', 46),
             ('too', 230),
             ('much', 338),
             ('lol', 124),
             ('use', 108),
             ('my', 2021),
             ('stuff', 79),
             ('spread', 16),
             ('love', 526),
             ("it's", 437),
             ('all', 925),
             ('right', 212),
             ('mission', 26),
             ('but', 1049),
             ('end', 83),
             ('son', 18),
             ('bitch', 40),
             ('n2k2k', 1),
             ('n2k', 56),
             ('myteam', 62),
             ('pic', 748),
             ('fm', 23),
             ('eghchcuyxe', 4),
             ('homedepot', 71),
             ('attention', 12),
             ('executive', 6),
             ('administrators', 4),
             ('if', 593),
             ('ever', 230),
             ('your', 706),
             ('stores', 35),
             ('are', 981),
             ('getting', 227),
             ('big', 158),
             ('delivery', 20),
             ('orders', 21),
             ('sent', 28),
             ('pallets', 3),
             ('bricks', 3),
             ('downtown', 3),
             ('areas', 7),
             ('you', 2018),
             ('effectively', 4),
             ('being', 198),
             ('mainly', 13),
             ('helping', 25),
             ('negotiate', 1),
             ('destruction', 6),
             ('private', 14),
             ('property', 10),
             ('sorry', 67),
             ('still', 425),
             ("won't", 64),
             ('condemn', 1),
             ("lowe's", 12),
             ('rainbow6game', 235),
             ('internet', 91),
             ('disconnected', 21),
             ('me', 1121),
             ('from', 732),
             ('without', 88),
             ('leaderboard', 9),
             ('had', 324),
             ('restart', 16),
             ('after', 307),
             ('restarting', 4),
             ('trying', 134),
             ('restore', 5),
             ('server', 57),
             ('would', 265),
             ('start', 97),
             ('having', 138),
             ('problems', 55),
             ('know', 267),
             ('because', 354),
             ('friends', 76),
             ('wondered', 1),
             ('servers', 118),
             ('especially', 40),
             ('treyarch', 18),
             ('call', 212),
             ('duty', 156),
             ('black', 174),
             ('ops', 89),
             ('3', 513),
             ('is', 2809),
             ('worst', 96),
             ('fucking', 357),
             ('ruined', 20),
             ('by', 480),
             ('glitch', 25),
             ('class', 43),
             ('havin', 2),
             ('ass', 129),
             ('losers', 8),
             ('fix', 299),
             ('can’t', 91),
             ('go', 339),
             ('into', 193),
             ('single', 34),
             ('match', 56),
             ('someone', 130),
             ('invisible', 4),
             ('whole', 95),
             ('round', 21),
             ('shit', 479),
             ('company', 129),
             ('west', 20),
             ('bit', 133),
             ('any', 197),
             ('hope', 88),
             ('good', 594),
             ('playoff', 2),
             ('finish', 27),
             ('’', 378),
             ('s', 306),
             ('slowly', 17),
             ('dying', 31),
             ('g2esports', 3),
             ('progressively', 1),
             ('worse', 49),
             ('least', 57),
             ('na', 12),
             ('few', 93),
             ('wins', 36),
             ('wonder', 28),
             ('everyone', 166),
             ("else's", 4),
             ('nomad', 6),
             ('such', 134),
             ('wtf', 167),
             ('face', 58),
             ('when', 522),
             ('found', 71),
             ('terminator', 14),
             ('factory', 7),
             ('not', 1028),
             ('set', 38),
             ('fan', 42),
             ('100', 130),
             ('speed', 43),
             ('red', 352),
             ('dead', 363),
             ('redemption', 259),
             ('2', 785),
             ('have', 1070),
             ('pc', 134),
             ('fire', 27),
             ('9', 70),
             ('w', 76),
             ('swear', 19),
             ('god', 106),
             ('edge', 34),
             ('redownloaded', 1),
             ('itslef', 2),
             ('onto', 15),
             ('pr', 10),
             ('computer', 30),
             ('ma', 5),
             ('update', 161),
             ('j', 35),
             ('will', 515),
             ('scream', 5),
             ('16h', 1),
             ('36', 5),
             ('project', 17),
             ('out', 687),
             ('later', 39),
             ("everyone's", 15),
             ('favorite', 97),
             ('boxes', 11),
             ('full', 74),
             ('tablets', 3),
             ('fill', 8),
             ('up', 493),
             ('classrooms', 2),
             ('desert', 3),
             ('hills', 4),
             ('school', 16),
             ('glendale', 3),
             ('students', 18),
             ('them', 343),
             ('ahead', 17),
             ('first', 262),
             ('online', 151),
             ('learning', 26),
             ('monday', 17),
             ('it’s', 158),
             ('thanks', 229),
             ('trial', 40),
             ('verizon', 390),
             ('we’re', 15),
             ('going', 338),
             ('easports', 50),
             ('no', 584),
             ('tone', 2),
             ('eamaddennfl', 275),
             ('mishaps', 2),
             ('point', 76),
             ('need', 174),
             ('amazon', 480),
             ('buys', 12),
             ('old', 113),
             ('chicago', 8),
             ('mayor', 4),
             ('claar', 3),
             ('happy', 184),
             ('bolingbrook', 3),
             ('il', 6),
             ('see', 390),
             ('there', 332),
             ('an', 553),
             ('coolrepublican', 1),
             ('told', 42),
             ('amz', 3),
             ('15', 78),
             ('hour', 42),
             ('comes', 53),
             ('paying', 19),
             ('repubs', 3),
             ('country', 15),
             ('which', 154),
             ('he', 217),
             ('patch', 57),
             ('illinois', 4),
             ('bolin', 2),
             ('called', 52),
             ('lapdhq', 2),
             ('brother', 24),
             ('was', 902),
             ('town', 10),
             ('back', 304),
             ('those', 91),
             ('intense', 6),
             ('story', 100),
             ('as', 586),
             ('hell', 109),
             ('enemies', 5),
             ('perfect', 70),
             ('dark', 25),
             ('zero', 21),
             ('ogreatgames', 1),
             ('products', 41),
             ('perfe', 1),
             ('kindly', 10),
             ('unban', 26),
             ('pubg', 231),
             ('unk', 497),
             ('each', 41),
             ('young', 24),
             ('entreprenuer', 1),
             ('lose', 40),
             ('little', 99),
             ('lives', 25),
             ('imrankhanpti', 8),
             ('nothing', 113),
             ('here', 255),
             ('folks', 28),
             ('amd', 16),
             ('supposedly', 3),
             ('testing', 17),
             ('navi', 5),
             ('could', 170),
             ('be', 1098),
             ('monster', 5),
             ('graphics', 52),
             ('processor', 12),
             ('seriously', 55),
             ('trouble', 20),
             ('dr', 23),
             ('rnlk', 1),
             ('people', 417),
             ('keep', 142),
             ('asking', 13),
             ('general', 12),
             ('public', 22),
             ("we'll", 15),
             ('allowed', 14),
             ('again', 244),
             ('one', 587),
             ('knows', 26),
             ('just', 1133),
             ('lets', 28),
             ('morons', 4),
             ('share', 71),
             ('unwelcome', 1),
             ('opinions', 3),
             ('wait', 252),
             ('updates', 34),
             ('logfta', 1),
             ('www', 23),
             ('greatly', 8),
             ('entering', 27),
             ('grand', 67),
             ('summoners', 27),
             ('watch', 202),
             ('video', 217),
             ('eventually', 18),
             ('won', 93),
             ('over', 284),
             ('gift', 43),
             ('retweet', 41),
             ('another', 177),
             ('chance', 90),
             ('win', 144),
             ('gs', 23),
             ('global', 42),
             ('now', 693),
             ('free', 159),
             ('5', 312),
             ('punch', 11),
             ('iron', 4),
             ('man', 185),
             ('unit', 38),
             ('chb3xp3yrf', 2),
             ('thank', 236),
             ('willing', 14),
             ('work', 218),
             ('today', 262),
             ('uploaded', 6),
             ('ton', 9),
             ('vods', 4),
             ('youtube', 161),
             ('among', 9),
             ('us', 340),
             ('borderlands', 284),
             ('alien', 2),
             ('overwatch', 180),
             ('clips', 34),
             ('highlights', 11),
             ('send', 20),
             ('sub', 6),
             ('maybe', 86),
             ('can', 592),
             ('make', 301),
             ('hobby', 2),
             ('saving', 16),
             ('amazing', 192),
             ('moments', 38),
             ('channel', 23),
             ('uc8w', 2),
             ('y', 50),
             ('played', 176),
             ('interesting', 97),
             ('poker', 7),
             ('quiz', 34),
             ('try', 102),
             ('dumb', 29),
             ('luck', 55),
             ('exciting', 70),
             ('rewards', 50),
             ('grk', 3),
             ('…', 251),
             ('shambles', 1),
             ('gta', 208),
             ('only', 318),
             ('person', 50),
             ('lobby', 16),
             ("i'm", 518),
             ('diamond', 13),
             ('also', 241),
             ('awful', 16),
             ('kids', 24),
             ('csensy', 1),
             ('team', 149),
             ("assassin's", 69),
             ('creed', 193),
             ('syndicate', 8),
             ('probably', 101),
             ('late', 27),
             ('night', 103),
             ('stream', 137),
             ('gang', 14),
             ('come', 144),
             ('some', 508),
             ('warzone', 40),
             ('runs', 23),
             ('we', 633),
             ('struggle', 10),
             ('catch', 8),
             ('dub', 7),
             ('yeticasual', 1),
             ('ty', 4),
             ('p', 66),
             ('ceyfcx0heds', 1),
             ('making', 108),
             ('crappy', 7),
             ('immortals', 3),
             ('til', 10),
             ('treasure', 8),
             ('redd', 19),
             ('itorke', 3),
             ('using', 68),
             ('zoom', 16),
             ('counterpart', 1),
             ('overcoming', 1),
             ('appsec', 1),
             ('programs', 4),
             ('remote', 8),
             ('working', 91),
             ('environment', 12),
             ('patrick', 1),
             ('carey', 1),
             ('director', 7),
             ('policy', 11),
             ('marketing', 15),
             ('synopsys', 1),
             ('data', 65),
             ('breach', 5),
             ('investigations', 2),
             ('report', 44),
             ('dbir', 1),
             ('around', 90),
             ('43', 4),
             ('breaches', 1),
             ('linked', 4),
             ('to…', 1),
             ('statistics', 6),
             ('org', 73),
             ('07', 24),
             ('ove…', 1),
             ('qjwjhzajjw', 1),
             ('looking', 131),
             ('csgo', 148),
             ('valorant', 25),
             ('r6s', 1),
             ('cod', 58),
             ('mean', 57),
             ('great', 350),
             ('opportunity', 18),
             ('help', 208),
             ('build', 23),
             ('something', 138),
             ('scratch', 3),
             ('maihs', 1),
             ('nieuw', 2),
             ('artikel', 2),
             ('brand', 32),
             ('ranked', 92),
             ('ladder', 10),
             ('arrived', 10),
             ('club', 20),
             ('hearthstone', 170),
             ('featuring', 7),
             ('lots', 13),
             ('bright', 7),
             ('stars', 18),
             ('dutchtwilight', 2),
             ('kathzilstudio', 2),
             ('nl', 5),
             ('name', 51),
             ('l', 25),
             ('playapex', 138),
             ('constant', 16),
             ('blue', 28),
             ('crashes', 28),
             ('ps4', 94),
             ('8', 53),
             ('matches', 10),
             ('succession', 1),
             ('caustic', 8),
             ('trap', 6),
             ('goes', 43),
             ('off', 222),
             ('down', 201),
             ('completely', 49),
             ('72', 6),
             ('points', 58),
             ('drain', 4),
             ('nba2k', 234),
             ('double', 12),
             ('bullshii', 1),
             ('pass', 45),
             ('bcuhz', 1),
             ('angry', 23),
             ('mf', 14),
             ('got', 376),
             ("isn't", 29),
             ('sending', 12),
             ('came', 46),
             ('our', 258),
             ('air', 19),
             ('conditioning', 1),
             ('quickly', 22),
             ('very', 275),
             ('professional', 11),
             ('friendly', 10),
             ('appreciated', 18),
             ('wore', 2),
             ('mask', 32),
             ('protect', 9),
             ('lori', 2),
             ('says', 69),
             ('google', 330),
             ('via', 151),
             ('webhorsemarketing', 2),
             ('birdeye', 8),
             ('aspen', 2),
             ('heating', 2),
             ("i've", 205),
             ('playing', 390),
             ('warrior', 11),
             ('favourite', 21),
             ('totally', 38),
             ('slammed', 1),
             ('vargoth', 2),
             ('drops', 19),
             ('bummer', 1),
             ('hm', 1),
             ('2013', 16),
             ('bought', 76),
             ('2018', 17),
             ('2024', 1),
             ('ps5', 228),
             ('2022', 3),
             ('swift', 5),
             ('seems', 59),
             ('reasonable', 2),
             ('even', 348),
             ('earlier', 14),
             ('anything', 76),
             ('until', 112),
             ('next', 175),
             ('activision', 27),
             ("blizzard's", 1),
             ('latest', 59),
             ('bring', 39),
             ('esports', 14),
             ('exclusively', 2),
             ('way', 153),
             ('went', 73),
             ('real', 114),
             ('damage', 25),
             ('gsght', 1),
             ('c', 54),
             ('l2vxv3', 1),
             ('swami', 3),
             ('ea', 110),
             ('drop', 31),
             ('equipment', 14),
             ('guru', 7),
             ('96', 3),
             ('93', 1),
             ('explain', 16),
             ('player', 93),
             ('showed', 13),
             ('signs', 3),
             ('unhappy', 2),
             ('rojo', 1),
             ('baystunna', 2),
             ('shutdownsafety', 3),
             ('biased', 2),
             ('ratings', 12),
             ('computers', 6),
             ('want', 264),
             ('ridiculous', 32),
             ('papers', 3),
             ('website', 31),
             ('bullshit', 38),
             ('easter', 2),
             ('eggs', 2),
             ('mlssmahut', 2),
             ('apparently', 23),
             ('mobile', 113),
             ('i’m', 176),
             ('glad', 45),
             ('pg', 3),
             ('alright', 12),
             ('geez', 1),
             ('scary', 14),
             ('pred', 4),
             ('flew', 2),

In [111]:
tokenizer.document_count

12188

In [ ]:
len(tokenizer.word_index)   # vacobulary size

18045

In [116]:
sequences=tokenizer.texts_to_sequences(df_train['Tweets'])

In [117]:
sequences

[[1384,
  2176,
  55,
  81,
  406,
  7,
  2,
  294,
  10,
  6,
  305,
  64,
  1018,
  19,
  6671,
  6672,
  110,
  6673,
  2804,
  4971,
  51,
  2549,
  4972,
  15,
  82,
  1211,
  55,
  166,
  81,
  6,
  4973,
  906,
  2805,
  2176,
  1685,
  2,
  509,
  10,
  1211,
  5,
  2806,
  454,
  11,
  3,
  10307,
  1019],
 [20,
  94,
  3529,
  121,
  54,
  4974,
  620,
  189,
  10308,
  4975,
  17,
  1594,
  247,
  131,
  6674,
  78,
  43,
  73,
  6675],
 [10309,
  6676,
  6677,
  385,
  2807,
  1438,
  15,
  82,
  6678,
  6679,
  92,
  240,
  30,
  12,
  5,
  219,
  3530,
  607,
  510,
  82,
  17,
  6680,
  6681,
  78,
  43,
  73,
  6682],
 [4,
  490,
  10310,
  4,
  490,
  6683,
  67,
  204,
  47,
  53,
  19,
  2,
  2040,
  10311,
  15,
  2,
  10312,
  4976,
  342,
  69,
  47,
  128,
  31,
  232,
  47,
  632,
  19,
  267,
  16,
  1385,
  433,
  4,
  490,
  6683],
 [3132, 4977, 42, 42, 401, 6, 3531, 385, 9, 137, 2550, 6684],
 [712,
  54,
  178,
  6685,
  41,
  65,
  80,
  1259,
  6,
  18,
  185,
  407,
  195,
  90,
  174,
  151,
  127,
  86,
  195,
  54,
  116,
  2808,
  336,
  128,
  633,
  155,
  103,
  293,
  321,
  13,
  408,
  65,
  1514,
  2,
  57],
 [75,
  28,
  172,
  19,
  2,
  1020,
  25,
  9,
  2,
  395,
  75,
  6,
  1386,
  7,
  6,
  728,
  10313,
  540,
  498,
  33,
  1134,
  4108],
 [448,
  1915,
  3133,
  4109,
  45,
  156,
  37,
  806,
  27,
  162,
  230,
  1260,
  1212,
  957,
  10,
  4978,
  7,
  4979,
  3,
  4980,
  2809,
  16,
  14,
  27,
  4110,
  190,
  454,
  1799,
  9,
  1058,
  10314,
  2,
  3134,
  7,
  1686,
  2177],
 [478, 4, 76, 491, 10315, 1916],
 [150,
  20,
  13,
  364,
  1213,
  22,
  34,
  13,
  18,
  378,
  6,
  2360,
  5,
  108,
  3,
  1515,
  13,
  18,
  112,
  4111,
  2,
  18,
  5,
  268,
  3,
  3532,
  11,
  2,
  531,
  132,
  343,
  261,
  549,
  4,
  129,
  12,
  96,
  13,
  419,
  9,
  2,
  18,
  10316,
  69,
  2,
  301],
 [4, 729, 57, 11],
 [1387,
  173,
  7,
  236,
  208,
  374,
  61,
  8,
  2,
  346,
  93,
  18,
  156,
  2,
  18,
  8,
  1261,
  70,
  1059,
  673,
  6686,
  278,
  2551,
  118,
  2,
  93,
  18,
  365,
  102,
  192,
  6,
  819,
  541,
  378,
  276,
  190,
  4112,
  10,
  6,
  349,
  93,
  1214,
  72,
  278,
  18,
  72,
  278,
  279],
 [2,
  1262,
  108,
  6,
  271,
  271,
  7,
  191,
  379,
  10,
  6,
  44,
  6687,
  984,
  25,
  11,
  87,
  113,
  1439,
  880,
  19,
  4981,
  162,
  10317,
  597,
  19,
  185,
  18,
  30,
  532,
  121,
  1917,
  8,
  162,
  25,
  6,
  355,
  791],
 [958,
  45,
  218,
  4113,
  3135,
  108,
  269,
  6,
  44,
  216,
  523,
  58,
  47,
  449,
  2,
  1687,
  2810],
 [45,
  4,
  108,
  26,
  757,
  13,
  689,
  3,
  277,
  674,
  97,
  91,
  138,
  32,
  132,
  24,
  757,
  13,
  270,
  15,
  985],
 [],
 [455,
  4,
  420,
  1321,
  3,
  327,
  45,
  30,
  94,
  3,
  820,
  10318,
  5,
  6688,
  14,
  1595,
  13,
  2178,
  907,
  112,
  12,
  3533,
  223,
  4,
  807,
  60,
  30,
  93,
  3534],
 [10319, 3535],
 [54, 1440, 39, 745, 19, 1596, 344],
 [2041,
  434,
  7,
  4982,
  2552,
  68,
  2,
  6689,
  30,
  4983,
  4114,
  54,
  1516,
  5,
  4984,
  1388,
  27,
  162,
  100,
  1441,
  7,
  121,
  135,
  127,
  7,
  242,
  1021,
  15,
  1442,
  231,
  157,
  3,
  6,
  730,
  19,
  83,
  1597,
  104,
  15],
 [584, 50, 6690, 15, 124, 5, 18, 6691, 3, 2, 421, 4, 209, 3, 1515],
 [71,
  1918,
  307,
  2553,
  2177,
  4115,
  4985,
  8,
  26,
  199,
  51,
  11,
  4986,
  3136,
  84,
  105,
  56,
  307,
  10320,
  110,
  690,
  4987,
  16,
  412,
  56,
  691,
  72,
  58,
  11,
  563,
  3,
  1322,
  105,
  27,
  32,
  4988,
  9,
  12,
  1598,
  19,
  238,
  4,
  24,
  50,
  294,
  170,
  8,
  86,
  533,
  17,
  4116,
  6692],
 [4, 569, 6693, 112, 13, 1097, 29, 9, 2179],
 [11,
  115,
  366,
  3137,
  607,
  337,
  49,
  318,
  5,
  219,
  39,
  3536,
  9,
  456,
  1060,
  1215,
  10321,
  17,
  713,
  10322],
 [2180, 1022, 154, 66, 714, 1098, 10323, 60, 731, 341, 1061, 2554],
 [50, 308, 3, 84, 141, 959],
 [1517,
  8,
  4989,
  1443,
  230,
  3537,
  5,
  11,
  211,
  23,
  6,
  3538,
  570,
  1919,
  16,
  60,
  550,
  1263,
  116,
  1135,
  11,
  10324],
 [69,
  53,
  77,
  257,
  1800,
  2,
  1920,
  1183,
  58,
  1599,
  23,
  1688,
  3,
  53,
  267,
  145,
  50,
  48,
  1023,
  5,
  11,
  21,
  960,
  14,
  129,
  28,
  2,
  4117,
  15,
  82,
  3,
  450,
  37,
  10325,
  4990,
  21,
  93,
  143,
  10,
  821],
 [10326,
  1136,
  157,
  2555,
  10,
  986,
  479,
  987,
  183,
  10,
  2,
  171,
  3,
  84,
  45,
  1389,
  14,
  356,
  122,
  6,
  277,
  71,
  675,
  7,
  336,
  715,
  185,
  127,
  10,
  203,
  369,
  3,
  254,
  41,
  1137,
  5,
  692,
  38,
  10,
  6,
  227,
  1214,
  111,
  48,
  369,
  2042,
  4118,
  198,
  758,
  78,
  43,
  73,
  6694],
 [149, 327, 47, 27, 1689, 3, 169],
 [136,
  4,
  3138,
  6,
  2361,
  4119,
  3,
  224,
  2362,
  101,
  123,
  6695,
  202,
  5,
  65,
  822,
  2043,
  5,
  434,
  4119,
  4,
  132,
  23,
  199,
  45,
  14,
  132,
  1264,
  22,
  6,
  3139,
  20,
  16,
  386,
  4,
  46,
  117,
  6,
  6696,
  39,
  7,
  1518,
  28,
  137,
  194,
  759,
  224,
  17,
  1138,
  6697,
  585],
 [4,
  205,
  9,
  12,
  345,
  2811,
  823,
  15,
  71,
  15,
  332,
  39,
  37,
  923,
  551,
  10,
  6,
  369,
  3,
  254,
  65,
  457,
  586,
  71,
  9,
  18,
  211,
  450,
  4991,
  144],
 [12,
  18,
  8,
  6,
  10327,
  135,
  18,
  15,
  112,
  175,
  28,
  127,
  5,
  4,
  109,
  129,
  48,
  587,
  9,
  13,
  1519,
  58,
  59,
  1801,
  146,
  162,
  1520,
  1099,
  31,
  10328,
  15,
  13,
  248],
 [466, 193, 2556, 334, 2, 346, 18, 7, 2, 174],
 [988,
  331,
  264,
  19,
  2,
  1690,
  255,
  183,
  62,
  732,
  1139,
  49,
  40,
  2181,
  3,
  2557,
  6,
  2812,
  82,
  17,
  10329,
  4120,
  17,
  483,
  10330,
  144],
 [322, 2813, 4992, 2182, 2558, 61, 127, 86, 1323, 11, 4993],
 [473, 11, 172, 38, 15, 1521, 5, 121, 10331],
 [10332,
  2,
  209,
  10,
  10333,
  4121,
  9,
  6,
  2559,
  367,
  1921,
  10334,
  10335,
  2814,
  7,
  2044,
  1600,
  10336,
  9,
  2,
  131,
  83,
  486,
  3539,
  6698,
  659,
  10337,
  486,
  29,
  449,
  370,
  4122,
  7,
  486,
  10338,
  27,
  4123,
  10339,
  3140,
  439,
  131,
  1100,
  247,
  10340,
  78,
  43,
  73,
  10341],
 [274,
  10,
  251,
  1062,
  10342,
  524,
  211,
  534,
  56,
  98,
  1390,
  10,
  14,
  211,
  176,
  1140,
  262,
  34,
  4994,
  10343],
 [122,
  6699,
  6700,
  6,
  855,
  54,
  361,
  2183,
  2184,
  10,
  1265,
  212,
  2815,
  1802,
  62,
  7,
  2816,
  1391,
  6701,
  9,
  6702,
  3540,
  6,
  2,
  54,
  361,
  576,
  1063,
  144],
 [263,
  27,
  14,
  104,
  3,
  53,
  2,
  1522,
  961,
  533,
  962,
  15,
  353,
  564,
  2185,
  9,
  6,
  10344,
  6,
  2560,
  3141,
  676,
  165,
  5,
  13,
  18,
  186,
  598,
  308,
  31,
  3142,
  525,
  186,
  2,
  4124],
 [152, 219, 2, 1922, 10345, 647, 420, 151, 10346, 11, 385, 22, 1141],
 [1691, 4, 88, 83, 69, 924, 13, 72, 1923],
 [634,
  3,
  118,
  139,
  1324,
  10347,
  1184,
  125,
  2045,
  5,
  2186,
  1392,
  16,
  170,
  6703,
  6,
  856,
  3,
  2363,
  6704,
  467,
  15,
  106,
  243,
  6705,
  2561,
  17,
  6706,
  6707],
 [179,
  81,
  85,
  2,
  230,
  2046,
  334,
  13,
  1216,
  54,
  1140,
  88,
  760,
  10348,
  15,
  13,
  6708,
  1325,
  136,
  67,
  6,
  10349],
 [10350,
  353,
  634,
  39,
  9,
  1523,
  5,
  4,
  422,
  11,
  9,
  1444,
  20,
  10351,
  10,
  160,
  5,
  4995,
  10,
  3541,
  516,
  6709,
  99,
  45,
  4,
  53,
  11,
  6,
  178,
  1692,
  4,
  76,
  128,
  195,
  423,
  312,
  207,
  178],
 [9,
  989,
  10352,
  517,
  632,
  19,
  106,
  202,
  173,
  7,
  236,
  5,
  212,
  746,
  1693,
  6710,
  3,
  224,
  25,
  2,
  241,
  11,
  28,
  440,
  186,
  211,
  53,
  62,
  306,
  1064,
  10353,
  17,
  555,
  10354],
 [124,
  4996,
  316,
  69,
  204,
  14,
  881,
  1694,
  2817,
  674,
  3,
  6,
  4997,
  34,
  6,
  10355,
  1524,
  92,
  357,
  1803,
  50,
  4998,
  7,
  190,
  6711,
  10356,
  6712,
  4999,
  276,
  8,
  6713,
  9,
  357,
  1924],
 [51,
  93,
  3143,
  12,
  8,
  58,
  77,
  134,
  3,
  84,
  857,
  93,
  5000,
  34,
  6,
  882,
  5,
  761,
  9,
  18,
  6714,
  6715],
 [59, 9, 6716],
 [1142,
  83,
  5,
  43,
  309,
  27,
  598,
  186,
  206,
  648,
  5001,
  43,
  8,
  1925,
  25,
  10357,
  1695],
 [88,
  4125,
  6717,
  283,
  6718,
  32,
  3,
  6719,
  86,
  177,
  40,
  446,
  6,
  762,
  1266,
  185,
  18,
  1445,
  6,
  2181,
  1326,
  880,
  3,
  1393,
  308,
  29,
  104,
  139,
  241,
  4,
  577,
  3,
  239,
  68,
  3542,
  11,
  68,
  5,
  6720,
  11,
  526,
  244,
  3543,
  3,
  35,
  4125,
  34,
  6721,
  1446,
  74,
  167,
  139,
  80,
  228,
  95,
  95,
  33,
  36,
  17,
  6722],
 [212, 361, 4126, 330, 32, 247, 10358, 264, 114],
 [59, 4127, 162, 338, 111, 1101],
 [95,
  95,
  95,
  4,
  107,
  261,
  542,
  19,
  41,
  524,
  3544,
  2364,
  283,
  925,
  963,
  112,
  51,
  86,
  10359,
  9,
  18,
  84,
  1804,
  10,
  565,
  10360,
  435,
  492,
  9,
  3545,
  339,
  10,
  254,
  330,
  204,
  26,
  118,
  11,
  1143,
  10361,
  116,
  5002,
  33,
  36,
  17,
  10362],
 [6, 199, 5003, 5004],
 [10363,
  1447,
  14,
  2,
  338,
  3546,
  5,
  242,
  397,
  1102,
  34,
  370,
  2,
  158,
  792,
  2,
  517,
  310,
  32,
  499,
  102,
  5,
  142,
  908,
  6723,
  17,
  517,
  1693],
 [42,
  10364,
  42,
  2047,
  284,
  6724,
  990,
  9,
  101,
  9,
  716,
  112,
  1217,
  5005,
  1805,
  3,
  693,
  25,
  60,
  774,
  284,
  313,
  5006,
  1394,
  926,
  158,
  168,
  926,
  17,
  168,
  5007,
  2818],
 [6725,
  86,
  6726,
  56,
  2819,
  571,
  6727,
  59,
  20,
  229,
  51,
  1021,
  302,
  54,
  413,
  293,
  2820,
  26,
  608],
 [6728, 6729, 4128, 2187, 2821, 4129, 9, 42, 42, 1267, 4130, 17, 483, 6730],
 [4,
  31,
  2,
  2,
  6731,
  4131,
  523,
  165,
  25,
  11,
  609,
  3,
  23,
  1103,
  2365,
  5008,
  63,
  288,
  5,
  11,
  132,
  23,
  456,
  10,
  402],
 [10365, 1268, 927, 5009, 4132, 610, 490, 6732, 151],
 [137,
  267,
  24,
  5010,
  65,
  1926,
  1269,
  5,
  13,
  323,
  24,
  166,
  81,
  16,
  6733,
  10366,
  10367,
  6734,
  2048,
  270,
  677,
  10368,
  94,
  2188],
 [621,
  40,
  44,
  40,
  272,
  88,
  95,
  110,
  928,
  3,
  23,
  208,
  2366,
  926,
  95,
  694,
  220,
  112,
  1806,
  2367,
  3144,
  42,
  42,
  3547,
  121,
  3548,
  6,
  10369,
  1696,
  16,
  1218,
  21,
  541,
  929,
  413,
  526,
  305,
  493,
  166,
  155,
  988,
  33,
  36,
  17,
  10370],
 [123, 32, 8, 227, 7, 392, 38, 69, 53, 4, 257, 162, 4133],
 [1601,
  5,
  1525,
  223,
  37,
  232,
  66,
  86,
  189,
  32,
  717,
  5,
  6735,
  6736,
  32,
  436,
  543,
  649,
  2189,
  133,
  2189,
  111,
  441,
  44,
  244,
  1270,
  330,
  44,
  564,
  52,
  380,
  455,
  808,
  12,
  86,
  7,
  2,
  79,
  1697],
 [442,
  3,
  396,
  3549,
  60,
  261,
  3,
  1271,
  13,
  3550,
  4134,
  293,
  25,
  648,
  1327,
  322,
  371,
  231,
  599,
  10,
  127,
  86],
 [6737, 29, 2, 79, 171, 18, 4, 156, 108, 1927, 6738, 409, 622],
 [3, 731, 147, 7, 37, 323, 85, 153, 148, 19, 6, 991, 1526, 342, 2, 421],
 [71,
  319,
  2190,
  2,
  5011,
  660,
  10371,
  6739,
  1024,
  3,
  10372,
  1024,
  3,
  10373,
  184,
  407,
  2,
  6739,
  2191,
  39,
  20,
  504,
  162,
  9,
  623,
  78,
  43,
  73,
  10374],
 [2, 517, 197, 1527, 747, 1025, 1144, 6740, 157, 3, 6741],
 [45, 90, 174, 5012, 990, 1528, 3551, 8, 3, 3145],
 [661,
  324,
  329,
  1698,
  695,
  312,
  1602,
  10375,
  30,
  131,
  964,
  10376,
  17,
  434,
  748,
  10377,
  10378,
  144],
 [635,
  196,
  4,
  46,
  26,
  468,
  13,
  5013,
  673,
  25,
  11,
  8,
  1928,
  4,
  180,
  4,
  88,
  6,
  1059],
 [89, 763, 111, 3146, 11, 68, 1018, 19, 13, 160],
 [159,
  126,
  4135,
  303,
  608,
  328,
  51,
  3,
  4136,
  2,
  535,
  5014,
  3,
  4137,
  4,
  107,
  104,
  3,
  1603,
  19,
  4138],
 [2, 458, 7, 142, 388, 8, 20, 930],
 [137,
  27,
  32,
  662,
  16,
  633,
  2,
  147,
  15,
  82,
  1272,
  1394,
  60,
  14,
  173,
  101,
  883,
  3,
  443,
  82,
  3,
  931,
  3147,
  1529,
  5,
  280,
  3148,
  1145,
  94,
  1328,
  926,
  71,
  448,
  6742,
  168,
  2368,
  6743],
 [51],
 [4,
  256,
  536,
  2,
  764,
  97,
  91,
  138,
  112,
  85,
  11,
  115,
  5,
  6744,
  10,
  122,
  6,
  178,
  5,
  11,
  29,
  20,
  44,
  59,
  733,
  6,
  314,
  7,
  267,
  172,
  38,
  25,
  11,
  29,
  52,
  44,
  5,
  59,
  229,
  3,
  35,
  32],
 [4, 46, 84, 13, 6745, 34, 141, 172, 38],
 [4,
  87,
  295,
  20,
  4139,
  229,
  10,
  203,
  324,
  329,
  3,
  255,
  39,
  1807,
  5,
  10379,
  15,
  2,
  18,
  1329],
 [2, 346, 142, 3, 793, 678, 72],
 [5015, 69, 4, 99, 600, 399, 12, 72],
 [80, 31, 858, 208, 5016, 224, 90, 17, 5017],
 [300, 39, 12, 5018, 73, 636, 15, 106, 1026, 3149, 3552, 1026, 6746],
 [42,
  42,
  6747,
  1604,
  32,
  495,
  284,
  284,
  313,
  1104,
  990,
  1929,
  1330,
  17,
  86,
  10380,
  78,
  43,
  73,
  10381],
 [308,
  25,
  57,
  10,
  6748,
  5,
  147,
  7,
  28,
  6749,
  1448,
  14,
  24,
  81,
  6,
  230,
  406,
  7,
  13,
  184,
  61,
  220,
  9,
  13,
  212,
  965,
  40,
  27,
  10382,
  15,
  44,
  1930,
  4,
  21,
  577,
  3,
  23,
  227,
  7,
  56,
  2822,
  3,
  3553,
  13,
  2369,
  663,
  65,
  315,
  408,
  3,
  255,
  484,
  187],
 [4, 52, 379, 16],
 [4,
  1395,
  1185,
  2,
  1065,
  3,
  372,
  19,
  99,
  6750,
  1449,
  2,
  2562,
  440,
  125,
  188,
  467,
  10383,
  15,
  448,
  243,
  2561,
  10384,
  17,
  4140,
  10385,
  79],
 [12, 8, 2, 4141, 2049, 7, 2, 54, 5019, 1396, 4141, 2049, 6751],
 [183,
  3554,
  49,
  1605,
  2823,
  68,
  208,
  71,
  1146,
  10,
  437,
  1699,
  141,
  4142,
  510,
  6,
  6752,
  63,
  14,
  46,
  289,
  215,
  566,
  141,
  4142,
  510,
  420,
  6753],
 [5020,
  10386,
  26,
  91,
  375,
  4,
  690,
  10387,
  16,
  4,
  134,
  5021,
  6,
  314,
  7,
  5021,
  4,
  88,
  100,
  400,
  2,
  1331,
  33,
  5,
  2563,
  10388,
  1397,
  5,
  10389],
 [763, 74, 315, 51, 62, 93, 458],
 [2564,
  89,
  165,
  19,
  2,
  10390,
  761,
  9,
  362,
  193,
  11,
  166,
  225,
  859,
  5,
  166,
  60],
 [2050, 114, 163, 308, 31, 2, 2565, 7, 363, 3555, 9, 2, 556],
 [346, 6754, 253],
 [30,
  2,
  275,
  64,
  650,
  2,
  469,
  16,
  105,
  27,
  527,
  62,
  277,
  505,
  77,
  734,
  649,
  2,
  884,
  470,
  147,
  7,
  100,
  53,
  26,
  24,
  289,
  3,
  282,
  471,
  5,
  53,
  26,
  24,
  289,
  3,
  282,
  292,
  226,
  147,
  7,
  100,
  53,
  26,
  24,
  289,
  3,
  282,
  292],
 [83, 55, 203, 194, 1390, 149, 14],
 [4,
  205,
  283,
  12,
  345,
  823,
  15,
  71,
  2,
  332,
  37,
  551,
  493,
  10,
  1027,
  6,
  369,
  141,
  3,
  254,
  457,
  586,
  71,
  3150,
  9,
  18,
  450,
  10391,
  144],
 [152,
  21,
  1273,
  22,
  39,
  2,
  2566,
  6755,
  565,
  5,
  4,
  29,
  109,
  86,
  18,
  9,
  474,
  459,
  552,
  6756],
 [4,
  60,
  115,
  745,
  518,
  129,
  4,
  107,
  20,
  1105,
  5,
  442,
  69,
  3556,
  3151,
  53,
  262,
  31,
  12,
  5,
  3557,
  14,
  27,
  104,
  3,
  23,
  1219,
  34,
  82,
  5,
  26,
  992],
 [152, 552, 205, 37, 860, 278, 18],
 [124,
  1274,
  74,
  6,
  6757,
  248,
  16,
  8,
  1275,
  3,
  2192,
  19,
  6758,
  122,
  5,
  122,
  145,
  119,
  99,
  35,
  6,
  1270,
  541,
  312,
  14,
  161,
  46,
  53,
  20,
  103,
  44,
  19,
  37,
  18,
  25,
  132,
  1066,
  40,
  35,
  2824,
  5,
  931,
  96,
  26,
  218,
  46,
  2825,
  3,
  195,
  1147,
  112,
  1322,
  1148],
 [45,
  14,
  180,
  5022,
  228,
  2370,
  2,
  885,
  63,
  99,
  637,
  30,
  28,
  774,
  37,
  1694,
  5023,
  37,
  297,
  1149,
  191,
  637,
  156,
  225,
  2567,
  15,
  1398,
  309,
  5,
  166,
  41,
  611,
  135,
  587,
  2193,
  18,
  66],
 [4, 334, 23, 544, 12, 15, 13],
 [58,
  4,
  1276,
  13,
  909,
  5,
  6759,
  12,
  8,
  67,
  661,
  270,
  1220,
  240,
  31,
  259,
  219,
  386,
  32,
  511,
  1150,
  328,
  105,
  25,
  121,
  504,
  11,
  10,
  6,
  44,
  775,
  572,
  274,
  3,
  1276,
  500,
  2826,
  49,
  4,
  386,
  5024,
  17,
  809,
  1140,
  10392],
 [263, 118, 5025, 19, 39, 190, 588, 3, 10393, 39, 7, 1606, 385, 11, 1700],
 [776, 932, 169, 124],
 [6, 5026, 6, 2567, 5, 6, 601, 5, 6, 10394, 5, 91, 66, 10395, 3152],
 [1607,
  118,
  12,
  3558,
  1148,
  6760,
  7,
  72,
  14,
  824,
  15,
  270,
  2568,
  97,
  91,
  138,
  32,
  550,
  21,
  910,
  825,
  15,
  6,
  1020,
  5,
  177,
  58,
  4,
  256,
  88,
  283,
  2,
  406,
  16,
  29,
  10396,
  22,
  11,
  93,
  4143,
  5,
  962,
  12,
  72,
  8,
  2371,
  6,
  10397,
  1277,
  664],
 [35, 1931, 7, 1219, 3153, 5, 3559, 10398, 3153, 638, 152, 253, 296, 17],
 [116, 2372, 127, 23, 31, 285, 433, 145, 33, 36, 17, 5027],
 [3560],
 [94, 1701, 108, 6, 230, 1932, 136],
 [66],
 [59,
  6761,
  4144,
  602,
  19,
  2,
  777,
  7,
  6762,
  5,
  233,
  94,
  5028,
  75,
  20,
  103,
  65,
  5029,
  5,
  10399,
  140,
  4,
  6763,
  679,
  29,
  247,
  220,
  115,
  157,
  3,
  1450,
  110,
  993,
  406,
  9,
  2827,
  269,
  98,
  2828,
  92,
  794,
  1151,
  14],
 [4, 534, 2, 1608, 7, 2, 4145, 25, 75, 155, 988, 5, 59, 603],
 [152,
  164,
  200,
  259,
  118,
  37,
  1221,
  2051,
  3,
  223,
  1451,
  81,
  162,
  1221,
  7,
  1106,
  381,
  38,
  9,
  13,
  2052],
 [180, 1332, 1066, 424, 140, 1186, 22],
 [89, 13, 248, 66, 69, 164, 161, 53, 12, 3, 43, 2569, 567],
 [283,
  2,
  5030,
  2810,
  8,
  1609,
  5031,
  159,
  126,
  10400,
  40,
  2570,
  1801,
  133,
  46,
  40,
  102,
  1610,
  1264,
  28,
  37,
  10401,
  5,
  233,
  2053],
 [54,
  6764,
  5032,
  10402,
  116,
  6765,
  5033,
  19,
  249,
  826,
  5,
  10403,
  3154,
  168,
  6766,
  17,
  54,
  6764,
  5032,
  111],
 [3,
  2,
  425,
  16,
  16,
  1702,
  795,
  2054,
  53,
  2829,
  13,
  1452,
  778,
  519,
  82,
  297,
  9,
  14,
  166,
  46,
  93,
  24,
  11,
  28,
  14,
  35,
  8,
  6767,
  777,
  247,
  252,
  810,
  5034,
  5,
  480,
  258,
  536,
  2055,
  757,
  10,
  212],
 [12, 8, 74, 4, 440, 3, 84, 150],
 [45, 90, 174, 151, 87, 113, 990, 1528, 3551, 8, 105, 3, 2373, 3145],
 [10404,
  157,
  10,
  986,
  479,
  987,
  183,
  2,
  171,
  3,
  84,
  45,
  14,
  356,
  6,
  277,
  71,
  675,
  336,
  715,
  185,
  127,
  10,
  203,
  369,
  3,
  254,
  41,
  1137,
  692,
  38,
  10,
  6,
  227,
  111,
  861,
  1808,
  758],
 [95, 95, 232, 8, 1028, 72, 231, 651, 3, 5, 301, 27, 186, 33, 36, 17, 6768],
 [5, 4, 410, 99, 35, 651, 6, 3155, 6769, 86, 778, 647, 323, 1333, 8, 2830],
 [2056,
  308,
  597,
  140,
  1933,
  6,
  448,
  1809,
  5,
  261,
  100,
  3561,
  602,
  281,
  14,
  46,
  1274,
  10,
  176,
  33,
  36,
  17,
  6770],
 [150,
  635,
  604,
  12,
  8,
  2,
  1334,
  64,
  4,
  254,
  731,
  6,
  18,
  5,
  731,
  1107,
  45,
  4,
  128,
  731,
  4,
  254,
  6,
  18,
  5,
  99,
  731,
  1107,
  5,
  239,
  115,
  13,
  1067,
  373,
  1107],
 [620,
  247,
  242,
  8,
  21,
  10405,
  1187,
  11,
  21,
  6,
  10406,
  7,
  2374,
  10407,
  10408,
  63,
  77,
  19,
  12,
  459,
  364,
  680],
 [4, 128, 129, 25, 6771, 181, 681, 7, 6711, 9, 2, 184, 3562, 80],
 [107,
  350,
  6772,
  13,
  35,
  115,
  30,
  169,
  110,
  10409,
  46,
  35,
  60,
  2,
  160,
  281,
  170,
  403,
  11,
  10,
  1453,
  66,
  50,
  206,
  91,
  278,
  4146,
  8,
  26,
  451,
  16,
  501,
  4,
  57],
 [652, 6773, 911, 1530, 60, 1277, 48, 2194, 745, 192, 5035, 2195, 160],
 [237],
 [46, 175, 111, 272, 102, 602, 59, 696, 7, 589, 1272, 51, 11],
 [1934,
  590,
  20,
  245,
  2571,
  51,
  2,
  5036,
  824,
  197,
  61,
  15,
  1935,
  4,
  3563,
  14,
  240,
  15,
  105,
  250,
  218,
  735,
  6,
  1703,
  50,
  2572,
  886,
  1444,
  2057,
  181,
  249,
  140,
  2,
  827,
  389,
  648,
  4,
  1029,
  195,
  11],
 [3564, 12, 98, 965, 1390, 4147, 4148, 94, 2375, 9],
 [2830, 1930],
 [383,
  403,
  72,
  9,
  732,
  96,
  7,
  2,
  469,
  16,
  47,
  1326,
  1704,
  3565,
  293,
  887,
  45,
  47,
  1030,
  15,
  1454,
  2573,
  888,
  263,
  1531],
 [887,
  14,
  280,
  276,
  10,
  261,
  6,
  44,
  3566,
  10,
  6,
  171,
  18,
  3567,
  6,
  1810,
  128,
  2831,
  10410,
  67,
  59,
  298,
  6774],
 [2,
  95,
  81,
  15,
  12,
  545,
  10,
  1611,
  429,
  226,
  268,
  3,
  774,
  6,

In [119]:
len(sequences[0])

46

In [120]:
len(sequences[1])

19

In [121]:
len(sequences[2])

27

In [122]:
from keras.utils import pad_sequences

In [123]:
sequences=pad_sequences(sequences, padding='pre')

In [124]:
sequences

array([[    0,     0,     0, ...,     3, 10307,  1019],
       [    0,     0,     0, ...,    43,    73,  6675],
       [    0,     0,     0, ...,    43,    73,  6682],
       ...,
       [    0,     0,     0, ...,    62,   222,   677],
       [    0,     0,     0, ...,    38, 18043,    17],
       [    0,     0,     0, ...,    43,    73, 10296]])

In [126]:
from tensorflow.keras.layers import SimpleRNN, Dense, Input, Embedding
from tensorflow.keras.models import Sequential

In [127]:
X=sequences

In [131]:
y=df_train['Sentiment'].values

In [132]:
X

array([[    0,     0,     0, ...,     3, 10307,  1019],
       [    0,     0,     0, ...,    43,    73,  6675],
       [    0,     0,     0, ...,    43,    73,  6682],
       ...,
       [    0,     0,     0, ...,    62,   222,   677],
       [    0,     0,     0, ...,    38, 18043,    17],
       [    0,     0,     0, ...,    43,    73, 10296]])

In [133]:
y

array([0, 2, 1, ..., 1, 1, 1])

In [135]:
from sklearn.model_selection import train_test_split

In [136]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [137]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9750, 166), (2438, 166), (9750,), (2438,))

In [138]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(99,1), return_sequences=False))
model.add(Dense(3, activation='softmax'))

c:\Users\Ankit\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [140]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [141]:
model.compile(
    optimizer='adam',
    metrics=['accuracy'],
    loss='sparse_categorical_crossentropy'
)

In [142]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=32)

Epoch 1/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.3372 - loss: 1.3827 - val_accuracy: 0.3601 - val_loss: 1.0947
Epoch 2/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.3631 - loss: 1.0948 - val_accuracy: 0.3450 - val_loss: 1.0979
Epoch 3/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step - accuracy: 0.3623 - loss: 1.0928 - val_accuracy: 0.3409 - val_loss: 1.0961
Epoch 4/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.3687 - loss: 1.0935 - val_accuracy: 0.3417 - val_loss: 1.0966
Epoch 5/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.3573 - loss: 1.0927 - val_accuracy: 0.3191 - val_loss: 1.1002
Epoch 6/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.3587 - loss: 1.0921 - val_accuracy: 0.3622 - val_loss: 1.0958
Epoch 7/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.3685 - loss: 1.0938 - val_accuracy: 0.3310 - val_loss: 1.0987
Epoch 8/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.3622 - loss: 1.0916 - val_accuracy: 0.3474 - val_loss: 1.0914
Epoch 9/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.3422 - loss: 1.0931 - val_accuracy: 0.3667 - val_loss: 1.0939
Epoch 10/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.3712 - loss: 1.0930 - val_accuracy: 0.3638 - val_loss: 1.0966

In [143]:
vocab_size=len(tokenizer.word_index) +1

In [145]:
vocab_size

18046

In [147]:
model2=Sequential()
model2.add(Input(shape=(99,)))
model2.add(Embedding(input_dim=vocab_size, output_dim=64))
model2.add(Dense(3,activation='softmax'))

In [149]:
model2.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 99, 64)         │     1,154,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 99, 3)          │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,155,139 (4.41 MB)

 Trainable params: 1,155,139 (4.41 MB)

 Non-trainable params: 0 (0.00 B)

In [161]:
model_final=Sequential([Embedding(
    input_dim=vocab_size,
    output_dim=128,
    input_length=166,
    mask_zero=True),
    SimpleRNN(32),
    Dense(3, activation='softmax')]
)

c:\Users\Ankit\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [162]:
model_final.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [163]:
model_final.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [164]:
model_final.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=32)

Epoch 1/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 10s 28ms/step - accuracy: 0.5235 - loss: 0.9755 - val_accuracy: 0.7125 - val_loss: 0.6994
Epoch 2/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 11s 36ms/step - accuracy: 0.8743 - loss: 0.3699 - val_accuracy: 0.7424 - val_loss: 0.6679
Epoch 3/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9600 - loss: 0.1192 - val_accuracy: 0.7227 - val_loss: 0.8054
Epoch 4/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 10s 34ms/step - accuracy: 0.9742 - loss: 0.0672 - val_accuracy: 0.7293 - val_loss: 0.8713
Epoch 5/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 11s 36ms/step - accuracy: 0.9835 - loss: 0.0449 - val_accuracy: 0.7203 - val_loss: 0.9624
Epoch 6/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - accuracy: 0.9826 - loss: 0.0438 - val_accuracy: 0.7285 - val_loss: 0.9907
Epoch 7/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 10s 31ms/step - accuracy: 0.9842 - loss: 0.0369 - val_accuracy: 0.7207 - val_loss: 1.0668
Epoch 8/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 9s 29ms/step - accuracy: 0.9819 - loss: 0.0378 - val_accuracy: 0.7162 - val_loss: 1.0557
Epoch 9/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 10s 33ms/step - accuracy: 0.9754 - loss: 0.0621 - val_accuracy: 0.7133 - val_loss: 1.1063
Epoch 10/10
305/305 ━━━━━━━━━━━━━━━━━━━━ 12s 39ms/step - accuracy: 0.9727 - loss: 0.0633 - val_accuracy: 0.7112 - val_loss: 1.1155

In [165]:
import pickle
with open("tokenizer.pkl", 'wb') as file:
    pickle.dump(tokenizer, file)

In [166]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.